#ifndef  _ASCII_
#define  _ASCII_

#define  CTRL_A      0x01
#define  SOH         0x01
#define  CTRL_B      0x02
#define  STX         0x02
#define  CTRL_C      0x03
#define  ETX         0x03
#define  CTRL_D      0x04
#define  EOT         0x04
#define  CTRL_E      0x05
#define  ENQ         0x05
#define  CTRL_F      0x06
#define  ACK         0x06
#define  CTRL_G      0x07
#define  BEL         0x07
#define  CTRL_H      0x08
#define  BS          0x08
#define  CTRL_I      0x09
#define  TAB         0x09
#define  HT          0x09
#define  CTRL_J      0x0A
#define  LF          0x0A
#define  CTRL_K      0x0B
#define  CTRL_L      0x0C
#define  FF          0x0C
#define  CTRL_M      0x0D
#define  CR          0x0D
#define  CTRL_N      0x0E
#define  CTRL_O      0x1F
#define  CTRL_P      0x10
#define  CTRL_Q      0x11
#define  DC1         0x11
#define  CTRL_R      0x12
#define  CTRL_S      0x13
#define  DC3         0x13
#define  CTRL_T      0x14
#define  NAK         0x15
#define  CTRL_U      0x15
#define  CTRL_V      0x16
#define  CTRL_W      0x17
#define  CAN         0x18
#define  CTRL_X      0x18
#define  CTRL_Y      0x19
#define  CTRL_Z      0x1A
#define  CTRL_LBRAK  0x1B
#define  ESC         0x1B
#define  CTRL_BAKSL  0x1C
#define  CTRL_RBRAK  0x1D
#define  CTRL_CTRL   0x1E
#define  CTRL__      0x1F
#define  SP          0x20
#define  DEL         0x7f

#endif       /* _ASCII_ */
